[2024-07-12T14:02:22.140+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vehicle_data_etl_DAG.run_events_etl manual__2024-07-12T14:02:19.911559+00:00 [queued]>
[2024-07-12T14:02:22.160+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vehicle_data_etl_DAG.run_events_etl manual__2024-07-12T14:02:19.911559+00:00 [queued]>
[2024-07-12T14:02:22.160+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-07-12T14:02:22.169+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_events_etl> on 2024-07-12 14:02:19.911559+00:00
[2024-07-12T14:02:22.174+0000] {standard_task_runner.py:57} INFO - Started process 75 to run task
[2024-07-12T14:02:22.179+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'vehicle_data_etl_DAG', 'run_events_etl', 'manual__2024-07-12T14:02:19.911559+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/vehicle_data_dag.py', '--cfg-path', '/tmp/tmphs4f6rvn']
[2024-07-12T14:02:22.183+0000] {standard_task_runner.py:85} INFO - Job 64: Subtask run_events_etl
[2024-07-12T14:02:22.221+0000] {task_command.py:410} INFO - Running <TaskInstance: vehicle_data_etl_DAG.run_events_etl manual__2024-07-12T14:02:19.911559+00:00 [running]> on host e13afd5ed18e
[2024-07-12T14:02:22.273+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ilyas' AIRFLOW_CTX_DAG_ID='vehicle_data_etl_DAG' AIRFLOW_CTX_TASK_ID='run_events_etl' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T14:02:19.911559+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-12T14:02:19.911559+00:00'
[2024-07-12T14:02:22.277+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-07-12T14:02:22.278+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/etl/vehicle_data && python3 main.py']
[2024-07-12T14:02:22.286+0000] {subprocess.py:86} INFO - Output:
[2024-07-12T14:02:34.016+0000] {subprocess.py:93} INFO - 2024-07-12 14:02:34.014 | INFO     | kaggle_pipeline.extract:get_data:30 - Dataset downloaded and extracted directly.
[2024-07-12T14:02:34.018+0000] {subprocess.py:93} INFO - 2024-07-12 14:02:34.015 | INFO     | kaggle_pipeline.extract:get_data:32 - Dataset downloaded and extracted successfully.
[2024-07-12T14:02:35.173+0000] {subprocess.py:93} INFO - 2024-07-12 14:02:35.173 | INFO     | kaggle_pipeline.load:load_data:33 - Data loaded successfully from /opt/***/etl/vehicle_data/vehicle_data_sales/car_prices.csv
[2024-07-12T14:02:35.177+0000] {subprocess.py:93} INFO - 2024-07-12 14:02:35.177 | ERROR    | kaggle_pipeline.load:initialize_pg_table:54 - Error initializing table (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
[2024-07-12T14:02:35.178+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2024-07-12T14:02:35.178+0000] {subprocess.py:93} INFO - connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
[2024-07-12T14:02:35.178+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2024-07-12T14:02:35.178+0000] {subprocess.py:93} INFO - 
[2024-07-12T14:02:35.178+0000] {subprocess.py:93} INFO - (Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-07-12T14:02:36.225+0000] {subprocess.py:93} INFO - 2024-07-12 14:02:36.223 | INFO     | kaggle_pipeline.load:load_data:33 - Data loaded successfully from /opt/***/etl/vehicle_data/vehicle_data_sales/car_prices.csv
[2024-07-12T14:02:36.333+0000] {subprocess.py:93} INFO - 2024-07-12 14:02:36.333 | ERROR    | kaggle_pipeline.transform:transform_data_type:40 - Error transforming data Cannot convert non-finite values (NA or inf) to integer
[2024-07-12T14:02:36.353+0000] {subprocess.py:93} INFO - 2024-07-12 14:02:36.353 | ERROR    | kaggle_pipeline.load:insert_data_to_pg:64 - Data transformation failed
[2024-07-12T14:02:36.416+0000] {subprocess.py:93} INFO - Dataset URL: https://www.kaggle.com/datasets/syedanwarafridi/vehicle-sales-data
[2024-07-12T14:02:36.708+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-12T14:02:36.754+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=vehicle_data_etl_DAG, task_id=run_events_etl, execution_date=20240712T140219, start_date=20240712T140222, end_date=20240712T140236
[2024-07-12T14:02:36.779+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-07-12T14:02:36.816+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
