[2024-07-12T02:29:23.842+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: events_etl_DAG.run_events_etl manual__2024-07-12T02:29:22.217034+00:00 [queued]>
[2024-07-12T02:29:23.848+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: events_etl_DAG.run_events_etl manual__2024-07-12T02:29:22.217034+00:00 [queued]>
[2024-07-12T02:29:23.848+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-07-12T02:29:23.855+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_events_etl> on 2024-07-12 02:29:22.217034+00:00
[2024-07-12T02:29:23.859+0000] {standard_task_runner.py:57} INFO - Started process 128 to run task
[2024-07-12T02:29:23.861+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'events_etl_DAG', 'run_events_etl', 'manual__2024-07-12T02:29:22.217034+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/events_dag.py', '--cfg-path', '/tmp/tmprp5p3352']
[2024-07-12T02:29:23.863+0000] {standard_task_runner.py:85} INFO - Job 55: Subtask run_events_etl
[2024-07-12T02:29:23.893+0000] {task_command.py:410} INFO - Running <TaskInstance: events_etl_DAG.run_events_etl manual__2024-07-12T02:29:22.217034+00:00 [running]> on host 7e0553ac55c9
[2024-07-12T02:29:23.942+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ilyas' AIRFLOW_CTX_DAG_ID='events_etl_DAG' AIRFLOW_CTX_TASK_ID='run_events_etl' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T02:29:22.217034+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-12T02:29:22.217034+00:00'
[2024-07-12T02:29:23.944+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-07-12T02:29:23.945+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/etl/events && python3 main.py']
[2024-07-12T02:29:23.949+0000] {subprocess.py:86} INFO - Output:
[2024-07-12T02:29:24.743+0000] {subprocess.py:93} INFO - 2024-07-12 02:29:24.743 | ERROR    | kaggle_pipeline.load:load_data:28 - File not found: ecommerce_data/events.csv
[2024-07-12T02:29:24.744+0000] {subprocess.py:93} INFO - No data inserted into PostgreSQL
[2024-07-12T02:29:24.993+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-12T02:29:25.010+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=events_etl_DAG, task_id=run_events_etl, execution_date=20240712T022922, start_date=20240712T022923, end_date=20240712T022925
[2024-07-12T02:29:25.047+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-07-12T02:29:25.059+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
