[2024-07-12T01:07:00.348+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: events_etl_DAG.run_events_etl manual__2024-07-12T00:58:03.014776+00:00 [queued]>
[2024-07-12T01:07:00.504+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: events_etl_DAG.run_events_etl manual__2024-07-12T00:58:03.014776+00:00 [queued]>
[2024-07-12T01:07:00.504+0000] {taskinstance.py:1308} INFO - Starting attempt 4 of 4
[2024-07-12T01:07:00.512+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_events_etl> on 2024-07-12 00:58:03.014776+00:00
[2024-07-12T01:07:00.516+0000] {standard_task_runner.py:57} INFO - Started process 200 to run task
[2024-07-12T01:07:00.518+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'events_etl_DAG', 'run_events_etl', 'manual__2024-07-12T00:58:03.014776+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/events_dag.py', '--cfg-path', '/tmp/tmplyu2vke1']
[2024-07-12T01:07:00.520+0000] {standard_task_runner.py:85} INFO - Job 43: Subtask run_events_etl
[2024-07-12T01:07:00.559+0000] {task_command.py:410} INFO - Running <TaskInstance: events_etl_DAG.run_events_etl manual__2024-07-12T00:58:03.014776+00:00 [running]> on host c007dc4aa1ba
[2024-07-12T01:07:00.614+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ilyas' AIRFLOW_CTX_DAG_ID='events_etl_DAG' AIRFLOW_CTX_TASK_ID='run_events_etl' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T00:58:03.014776+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-12T00:58:03.014776+00:00'
[2024-07-12T01:07:00.619+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-07-12T01:07:00.619+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/etl/events && python3 main.py']
[2024-07-12T01:07:00.625+0000] {subprocess.py:86} INFO - Output:
[2024-07-12T01:07:01.439+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-07-12T01:07:01.440+0000] {subprocess.py:93} INFO -   File "main.py", line 9, in <module>
[2024-07-12T01:07:01.441+0000] {subprocess.py:93} INFO -     from kaggle_pipeline.extract import Extractor
[2024-07-12T01:07:01.441+0000] {subprocess.py:93} INFO -   File "/opt/***/etl/kaggle_pipeline/extract.py", line 1, in <module>
[2024-07-12T01:07:01.441+0000] {subprocess.py:93} INFO -     import kaggle
[2024-07-12T01:07:01.441+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/kaggle/__init__.py", line 7, in <module>
[2024-07-12T01:07:01.442+0000] {subprocess.py:93} INFO -     api.authenticate()
[2024-07-12T01:07:01.442+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/kaggle/api/kaggle_api_extended.py", line 400, in authenticate
[2024-07-12T01:07:01.442+0000] {subprocess.py:93} INFO -     self.config_file, self.config_dir))
[2024-07-12T01:07:01.442+0000] {subprocess.py:93} INFO - OSError: Could not find kaggle.json. Make sure it's located in /home/***/.kaggle. Or use the environment method.
[2024-07-12T01:07:01.507+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-12T01:07:01.520+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-12T01:07:01.523+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=events_etl_DAG, task_id=run_events_etl, execution_date=20240712T005803, start_date=20240712T010700, end_date=20240712T010701
[2024-07-12T01:07:01.556+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 43 for task run_events_etl (Bash command failed. The command returned a non-zero exit code 1.; 200)
[2024-07-12T01:07:01.571+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-07-12T01:07:01.586+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
