[2024-07-12T00:58:04.741+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: events_etl_DAG.run_events_etl manual__2024-07-12T00:58:03.014776+00:00 [queued]>
[2024-07-12T00:58:04.746+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: events_etl_DAG.run_events_etl manual__2024-07-12T00:58:03.014776+00:00 [queued]>
[2024-07-12T00:58:04.746+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-07-12T00:58:04.755+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_events_etl> on 2024-07-12 00:58:03.014776+00:00
[2024-07-12T00:58:04.759+0000] {standard_task_runner.py:57} INFO - Started process 66 to run task
[2024-07-12T00:58:04.762+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'events_etl_DAG', 'run_events_etl', 'manual__2024-07-12T00:58:03.014776+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/events_dag.py', '--cfg-path', '/tmp/tmpkmo3p6nj']
[2024-07-12T00:58:04.764+0000] {standard_task_runner.py:85} INFO - Job 38: Subtask run_events_etl
[2024-07-12T00:58:04.795+0000] {task_command.py:410} INFO - Running <TaskInstance: events_etl_DAG.run_events_etl manual__2024-07-12T00:58:03.014776+00:00 [running]> on host b61754df636c
[2024-07-12T00:58:04.841+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ilyas' AIRFLOW_CTX_DAG_ID='events_etl_DAG' AIRFLOW_CTX_TASK_ID='run_events_etl' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T00:58:03.014776+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-12T00:58:03.014776+00:00'
[2024-07-12T00:58:04.843+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-07-12T00:58:04.843+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd ${AIRFLOW_PROJ_DIR}/etl/events && python3 main.py']
[2024-07-12T00:58:04.850+0000] {subprocess.py:86} INFO - Output:
[2024-07-12T00:58:04.862+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /etl/events: No such file or directory
[2024-07-12T00:58:04.862+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-12T00:58:04.871+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-12T00:58:04.873+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=events_etl_DAG, task_id=run_events_etl, execution_date=20240712T005803, start_date=20240712T005804, end_date=20240712T005804
[2024-07-12T00:58:04.880+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 38 for task run_events_etl (Bash command failed. The command returned a non-zero exit code 1.; 66)
[2024-07-12T00:58:04.903+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-07-12T00:58:04.913+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
