[2024-07-12T00:50:17.950+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: events_etl_DAG.run_events_etl scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T00:50:17.958+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: events_etl_DAG.run_events_etl scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-12T00:50:17.958+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-07-12T00:50:17.976+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_events_etl> on 2024-07-11 00:00:00+00:00
[2024-07-12T00:50:17.990+0000] {standard_task_runner.py:57} INFO - Started process 60 to run task
[2024-07-12T00:50:18.000+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'events_etl_DAG', 'run_events_etl', 'scheduled__2024-07-11T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/events_dag.py', '--cfg-path', '/tmp/tmp3aafzx6c']
[2024-07-12T00:50:18.007+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask run_events_etl
[2024-07-12T00:50:18.068+0000] {task_command.py:410} INFO - Running <TaskInstance: events_etl_DAG.run_events_etl scheduled__2024-07-11T00:00:00+00:00 [running]> on host 4c5dc08e81bf
[2024-07-12T00:50:18.141+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ilyas' AIRFLOW_CTX_DAG_ID='events_etl_DAG' AIRFLOW_CTX_TASK_ID='run_events_etl' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T00:00:00+00:00'
[2024-07-12T00:50:18.148+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-07-12T00:50:18.149+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd ../etl/events && python3 main.py']
[2024-07-12T00:50:18.157+0000] {subprocess.py:86} INFO - Output:
[2024-07-12T00:50:18.165+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: ../etl/events: No such file or directory
[2024-07-12T00:50:18.165+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-12T00:50:18.173+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-12T00:50:18.176+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=events_etl_DAG, task_id=run_events_etl, execution_date=20240711T000000, start_date=20240712T005017, end_date=20240712T005018
[2024-07-12T00:50:18.185+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 32 for task run_events_etl (Bash command failed. The command returned a non-zero exit code 1.; 60)
[2024-07-12T00:50:18.225+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-07-12T00:50:18.239+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
